sudo: required
language: c
compiler:
- clang
- gcc
script:
- git clone https://github.com/rumblesan/bclib.git
- pushd bclib/build
- pwd
- cmake ..
- make
- make test
- sudo make install
- popd
- cd build
- cmake ..
- make
- make test