sudo: required
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - bison
    - flex
script:
- git clone https://github.com/rumblesan/bclib.git
- pushd bclib/build
- pwd
- cmake -DINSTALL_INCLUDE_DIR:STRING=/usr/local/include -DINSTALL_LIB_DIR:STRING=/usr/local/lib ..
- make
- make test
- sudo make install
- popd
- cd build
- ls
- cmake -DINSTALL_INCLUDE_DIR:STRING=/usr/local/include -DINSTALL_LIB_DIR:STRING=/usr/local/lib ..
- make
- make test