sudo: required
language: c
compiler:
- clang
- gcc
before_script:
- git clone https://github.com/rumblesan/bclib.git
- cd bclib/build
- cmake ..
- make
- make test
- sudo make install
script:
- cd build
- cmake ..
- make
- make test